### ISSUE TITLE
why don't merge my PR.

### ISSUE THREAD

**Issue by fun1355** [EndoSakura/extract_bilibili_video#1]
I rewrite your code, so that it work under both Windows and Linux, so Linux version code needn't track Windows version individually.

**Comment by EndoSakura** [comment]
emmm&nbsp; OK



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 19, 2021 12:20 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [EndoSakura/extract_bilibili_video] why don't merge my PR. (#1)




 
I rewrite your code, so that it work under both Windows and Linux, so Linux version code needn't track Windows version individually.

**Comment by EndoSakura** [comment]
I deleted and rebuilt the&nbsp;repositoriy. So your PR is gone。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EndoSakura/extract_bilibili_video"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 中午12:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[EndoSakura/extract_bilibili_video] why don't merge my PR. (#1)





 
I rewrite your code, so that it work under both Windows and Linux, so Linux version code needn't track Windows version individually.

**Comment by fun1355** [comment]
This branch is 12 commits ahead, 7 commits behind EndoSakura:main. 

There isn’t anything to compare.

EndoSakura:main and fun1355:main are entirely different commit histories. 
---
I also can't recommit the PR, thongh i forked your new repo again....

**Comment by fun1355** [comment]
I have to edit your code in website file by file separately, I just want to keep code unit
